### ISSUE TITLE
regels bij 'related observation'

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GLD#10]
[BRO standaardisatieteam]
## Type issue
Publieke consultatie

## Waar
paragraaf Gerelateerde observaties (3.5.2.2 in de respec versie) en gegevensdefinitie

## Beschrijving
In de gegevensdefinitie ontbreken regels over de gerelateerde observatie. In de toelichting klopt het niet helemaal met wat er in de regels staat (die nu niet zichtbaar zijn)

## Oplossingsrichting
Tekst in de toelichting herschrijven en de regels toevoegen in de gegevensdefinitie.

**Comment by AnnitaVijverberg** [comment]
De regel en toelichting afstemmen op hetgeen wordt besproken in de sprintreview van 19 december. 
Een aanvullende regel is mogelijk dat de gerelateerde observaties, zijnde voorlopige observaties, in de tijd moeten overeenkomen (overlappen) met de volledig beoordeelde reeks, er mag geen gerelateerde periode ontbreken.

**Comment by swppulles** [comment]
Hoe wordt vastgelegd welke observaties gerelateerd zijn? Extra attribuut?

**Comment by AnnitaVijverberg** [comment]
Regels op gerelateerder observatie komen, naar aanleiding van de sprintreview van 19 dec 2019, te vervallen #43 en #44.
De gerelateerde observaties kunnen aangegeven worden door het obsevatie ID te registreren van de gerelateerde observaties. Hiervoor zal een algemene check gebouwd worden dat de opgegeven ID's moeten bestaan binnen het betreffende GLD en dat het observatie ID's moeten zijn (en bijv geen proces ID's).

**Comment by AnnitaVijverberg** [comment]
In de toelichtende tekst is toegevoegd dat bij het registreren van gerelateerde observaties gebruik gemaakt wordt van het observatie ID.
Ook zijn de regels aangepast conform de uitspraken tijdens de reviewsessie (gerelateerde observaties zijn niet verplicht). De toelichtende tekst is aangepast: indien de observaties waarop een volledig beoordeelde reeks is gebaseerd aanwezig zijn, moeten ze met gerelateerde observaties aangegeven worden. Er vindt geen check op plaats omdat ze kunnen ontbreken. Dit is conform besproken is op de reviewsessie van 19 december 2019.
