### ISSUE TITLE
Datum metadata: catalogus (BRO) vs. uitwisselformaat (WaterML)

### ISSUE THREAD

**Issue by weeginkjw** [BROprogramma/GLD#114]
- bevinding bouw
- de catalogus geeft voor datum metadata onder IMBRO/A: onvolledigeDatum
- de gco standaard (uitwisselformat) gebruikt hiervoor "dateStamp", maar gco:Date ondersteunt alleen gYear, gMonthYear en gDatedate, en dus niet datum=onbekend

Suggestie: geef in de Catalogus aan dat datum=onbekend niet is toegestaan

**Comment by HanWelmer** [comment]
Zie paragraaf 3.2.4 van de berichtencatalogus:

Het attribuut dateStamp (datum metadata) heeft als type een gco:Date_Type. In de GLD gegevenscatalogus het dit attribuut als type een Datum onder kwaliteitsregime IMBRO en een OnvolledigeDatum onder IMBRO/A. Onderstaande voorbeelden geven mogelijke waarden met afnemende nauwkeurigheid.

<gmd:dateStamp>
  <gco:Date>2018-01-28</gco:Date>
</gmd:dateStamp>

<gmd:dateStamp>
  <gco:Date>2018-01</gco:Date>
</gmd:dateStamp>

<gmd:dateStamp>
  <gco:Date>2018</gco:Date>
</gmd:dateStamp>

<gmd:dateStamp gco:nilReason="unknown"/>

**Comment by weeginkjw** [comment]
BRO-LV team gaat dit implementeren

**Comment by HanWelmer** [comment]
Jan-Willem Weegink: https://github.com/BROprogramma/GLD/issues/114 is inmiddels door ons (LV team) correct geïmplementeerd en kan wat mij betreft gesloten worden.
