### ISSUE TITLE
waardelijst kwaliteitsregime

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GLD#12]
[Janco van Gelderen, Provincie Utrecht]
## Type issue
Publieke consultatie

## Waar
3.1.5

## Beschrijving
Wat is de inhoud van de Domeinwaarden? Dit komt niet terug in Artikel 2 bijlagen.

## Oplossingsrichting
lijst domeinwaarden toevoegen.

**Comment by swppulles** [comment]
Staat in document Inleiding op de catalogus van 7-11-2019

**Comment by harryvanmanen** [comment]
zie ook issue 49

**Comment by AnnitaVijverberg** [comment]
De waardelijst van 'kwaliteitsregime' staat inderdaad niet in artikel 2 van de GLD catalogus. Dit is een onderdeel van de gegevensdefinitie dat geldt voor alle registratieobjecten en daarom staat het in het document 'Inleiding catalogus GLD' namelijk in paragraaf 2.4 van deze inleiding.
