### ISSUE TITLE
Mogelijkheid om via REST api een tijdsinterval op te geven bij ophalen GLD.

### ISSUE THREAD

**Issue by OnnoEbbens** [BROprogramma/GLD#125]
Ik weet niet zeker of het de bedoeling is dat ik dit hier post. Voel je vrij om deze issue te verwijderen als dit niet de juiste plek is.

Ik maak gebruik van REST API om een grondwaterstandendossier (GLD) op te vragen:
https://publiek.broservices.nl/gm/gld/v1/swagger-ui/#/default/objects

Regelmatig ben ik geïnteresseerd in een langjarige tijdreeks waarbij een meting van 1x per dag voldoende is. Op dit moment haal ik daarvoor de volledige reeks op. Soms heeft deze reeks een meetinterval van 1x per uur waardoor ik 24x zoveel data ophaal als dat ik nodig heb. Als ik bijvoorbeeld de meetreeks van broId GLD000000009378 ophaal vanaf 1 januari 2020 tot nu ([link](https://publiek.broservices.nl/gm/gld/v1/objects/GLD000000009378?observationPeriodBeginDate=2020-01-01)), krijg ik 9,1 MB aan data terug.

Om de hoeveelheid data te beperken die ik opvraag zou ik graag de optie hebben om naast een begin- en einddatum van de reeks ook het gewenste meetinterval mee te kunnen geven in mijn verzoek. Is het mogelijk om deze optie toe te voegen?

**Comment by fterpstra** [comment]
Hoi Onno,
Voor dit soort feature requests hebben we de BRO servicedesk: https://basisregistratieondergrond.nl/service-contact/formulieren/contactformulier/ als je deze vraag daar indient wordt hij in behandeling genomen en wordt je per mail op de hoogte gehouden over de status

**Comment by OnnoEbbens** [comment]
Dank voor de snelle reactie, ik post het daar!
