### ISSUE TITLE
waardelijst registratiestatus

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GLD#15]
[Janco van Gelderen, Provincie Utrecht]
## Type issue
Publieke consultatie

## Waar
3.2.2

## Beschrijving
wat is de waardelijst van registratiestatus? Dit komt niet terug in Artikel 2 bijlagen

## Oplossingsrichting
lijst domeinwaarden toevoegen.

**Comment by harryvanmanen** [comment]
Volgens mij: zie 1.1 Waardelijst

**Comment by AnnitaVijverberg** [comment]
In artikel 2, paragraaf (tabel) 1.1 staat de waardelijst met mogelijke actuele fases van registratie waarin het object zich bevindt: de registrtiestatus.
