### ISSUE TITLE
Voorbeeld bij: tijdstip resultaat

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GLD#21]
[Janco van Gelderen, Provincie Utrecht]
## Type issue
Publieke consultatie

## Waar
3.5.3

## Beschrijving
dit is erg moelijk te lezen en te  begrijpen zonder uitgewerkt voorbeeld

## Oplossingsrichting
een fictief voorbeeld toevoegen in de bijlagen

**Comment by swppulles** [comment]
Mijn eerste gedachte bij het doorlezen van 3.5.3 was "wat voegt dit attribuut toe?". De attribuut-waarde is uit andere attribuut-waarden te halen, zie toelichting bij 3.5.3.  Waarom moet hetzelfde gegeven twee keer worden opgegeven? Of: de BRO kan de waarde zelf afleiden, en dan kan in het domeinmodel bij 3.5 "+/tijdstip resultaat" komen te staan, een slash toevoegen dus. Maar ... bij reguliere meting EN volledig beoordeeld ligt dit anders. In dat geval is de waarde niet uit meetdata te halen. 
Heeft ook relatie met 3.6.1!

**Comment by harryvanmanen** [comment]
Voor de volgende regel kan de DatumTijd automatisch worden bepaald: _
_De observatieperiode overlapt niet met de observatieperiode van andere entiteiten
Observatie uit hetzelfde Grondwaterstandonderzoek waarvoor geldt:
 dat de waarde van het attribuut type observatie gelijk is aan de waarde van
ditzelfde attribuut in de huidige entiteit EN
 dat de waarde van het attribuut mate beoordeling gelijk is aan de waarde van
ditzelfde attribuut in de huidige entiteit.__

Bij de toelichting duidelijk aangeven waarom dit attribuut is opgenomen.

**Comment by AnnitaVijverberg** [comment]
Het attribuut is een in waterML verplicht attribuut. De bronhouder moet het daarom aanleveren (zie een verdere toelichting hierover #46). We hebben de tekst van paragraaf 1.5.2 van de toelichting (over de observatie waaronder het tijdstip resultaat)  aangevuld om dit attribuut te verduidelijken.
