### ISSUE TITLE
Nut van: proces ID

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GLD#22]
[Janco van Gelderen, Provincie Utrecht]
## Type issue
Publieke consultatie

## Waar
3.8.1

## Beschrijving
Onduidelijk attribuut. Geen idee waar dit attribuut voor nodig is.

**Comment by rbv305** [comment]
als ik het goed begrijp is dit attribuut ondermeer voor bedoeld om een onderscheid te maken in controlemetingen en reguliere metingen

**Comment by swppulles** [comment]
Volgens mij kun je een eerder opgegeven proces ID gebruiken bij een nieuw op te voeren observatie (uiteraard als de attribuut-waarden van Observatieproces gelijk zijn).

**Comment by harryvanmanen** [comment]
Voor mij is dit ook onduidelijk. Toelichten waarom proces ID nodig is.

**Comment by BartJandeLeuw** [comment]
Tip: Bij het realiseren en testen is het makkelijker als de naam Observatieproces-ID wordt gehanteerd.

**Comment by AnnitaVijverberg** [comment]
Het proces ID is hernoemd naar observatieproces ID naar aanleiding van de melding van BartJan. Het attribuut is vanuit WaterML (en Observations & Measurements) verplicht. Daarnaast is het een zeer bruikbaar attribuut bij o.a. aanlevering: Bij aanlevering van een observatie met hetzelfde proces als al geregistreerd is, is het mogelijk om alleen het observatieproces ID aan te leveren. Alle andere observatieproceskenmerken worden dan niet aangeleverd.
We hebben dit in de toelichting verduidelijkt.
