### ISSUE TITLE
Bij: type luchtdrukcompensatie, merken opnemen

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GLD#24]
[Janco van Gelderen, Provincie Utrecht]
## Type issue
Publieke consultatie

## Waar
3.8.4

## Beschrijving
Ook hier is het mogelijk handiger als op basis van het type drukopnemer een keuze kan worden aangegeven.

## Oplossingsrichting
vb Keller type DCX22AA = relatieve druksensor valt in categorie 'putlocatiemeting' wellicht hier een extra lijst voor opmaken?

**Comment by harryvanmanen** [comment]
Ook de mogelijkheid behouden om dit beperketer te specificeren (als dat niet (meer) bekend is)

**Comment by AnnitaVijverberg** [comment]
Ook voor het type luchtdrukcompensatie is het niet aan de BRO om de huidige merken en type te standaardiseren (zie ook issue #23 )
Voor historische data, waar niet meer volledig te achterhalen welk instrument en/of welk type luchtdrukcompensatie is gebruikt, kan gekozen worden voor een onbekend type meetinstrument en in het geval van een druksensor voor een type luchtdrukcompensatie: onbekend
