### ISSUE TITLE
Nut van: procestype

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GLD#25]
[Janco van Gelderen, Provincie Utrecht]
## Type issue
Publieke consultatie

## Waar
3.8.5

## Beschrijving
Is dit nou wel een logisch extra attribuut als altijd algoritme wordt ingevuld?

## Oplossingsrichting
attribuut laten vervallen

**Comment by harryvanmanen** [comment]
Heeft volgens mij verplichte velden in WaterML te maken en kan  automatisch  worden ingevuld zodat dataleverancier daar geen "zorgen" om heeft.

**Comment by AnnitaVijverberg** [comment]
Procestype is een verplicht attribuut in WaterML, daarom moet het aangeleverd worden en kan het niet worden ingevuld door de BRO (zie ook issue #46 ). Tijdens de sprintreview van 24 oktober is bediscussieerd en toegelicht wat de voordelen zijn van het volgen van de WaterML standaard (o.a. dat op WaterML gebaseerde software direct gebruikt kan worden). Daarnaast wordt dit attribuut relevant als mogelijk op een later moment ook ruwe meetwaarden opgenomen worden. In die gevallen zal de waardelijst van dit attribuut aangevuld worden met andere waarden.
