### ISSUE TITLE
Waardelijst status kwaliteitscontrole

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GLD#27]
[Janco van Gelderen, Provincie Utrecht]
## Type issue
Publieke consultatie

## Waar
3.11.1

## Beschrijving
onduidelijk welke waarden in de waardenlijst staan, deze ontbreekt in de bijlagen

## Oplossingsrichting
waardenlijst opgeven

**Comment by rbv305** [comment]
In Tabel 1.9 staan de waarden voor de status kwaliteitscontrole

**Comment by AnnitaVijverberg** [comment]
De waardelijst StatusKwaliteitscontrole is opgenomen in 1.9 van Artikel 2.
