### ISSUE TITLE
inhoud van waardelijst registratiestatus

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GLD#30]
[Janco van Gelderen, Provincie Utrecht]
## Type issue
Publieke consultatie

## Waar
Artikel 2, 1.1

## Beschrijving
Onduidelijk wat je hier nu kiest, je kunt standaard kiezen voor 'geregistreerd' of 'voltooid' in feite lever je altijd waarden in die niet gecorrigeerd worden, tenzij ze alleen voorlopig zijn beoordeeld.

## Oplossingsrichting
Moet er nog een status 'gecorrigeerd' komen? Als eerder geleverde data zijn overschreven?

**Comment by rbv305** [comment]
In artikel 3.2.5 kun je aangeven of de meetwaarde gecorrigeerd is

**Comment by AnnitaVijverberg** [comment]
Alle attributen van de registratiegeschiedenis, dus alle onderdelen van paragraaf 3.2, worden automatisch gegenereerd door de basisregistratie ondergrond. Deze attributen worden niet aangeleverd door de bronhouder/dataleverancier.
In het geval van de registratiestatus, wordt automatisch geregistreerd, aangevuld of voltooid ingevuld. Na insturen van het GLD-Start brondocument zal de registratiestatus ‘geregistreerd’ zijn. Wanneer aanvullingen worden aangeleverd middels het brondocument GLD-aanvulling, zal de registratiestatus ‘aangevuld’ zijn. Dit brondocument gebruik je voor alle aanvullende gegevens: bij een nieuwe observatie van een nieuwe periode, bij een nieuwe observatie van volledig beoordeelde gegevens etc. Nadat brondocument GLD-voltooien of GLD-volledig is ingestuurd staat de registratiestatus op ‘voltooid’. Het GLD kan bij registratiestatus ‘voltooid’  niet verder aangevuld worden. Het GLD is dan afgesloten.

Wanneer al geregistreerde gegevens worden gecorrigeerd, is dat terug te vinden bij 3.2.5. gecorrigeerd. Hier is automatisch ‘ja’ geregistreerd als er een correctieverzoek is ingestuurd.
