### ISSUE TITLE
Welke meetprocedure wordt gebruikt?

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GLD#31]
[Janco van Gelderen, Provincie Utrecht]
## Type issue
Publieke consultatie

## Waar
Artikel 2, 1.2

## Beschrijving
Geen idee welk we als provincies nu uit deze lijst gaan kiezen

## Oplossingsrichting
Als provincies kunnen we hier standaard een keuze maken?

**Comment by rbv305** [comment]
mooie vraag om uit te zetten bij het platform !

**Comment by AnnitaVijverberg** [comment]
We gaan ervan uit dat elke bronhouder volgens een bepaalde meetprocedure werkt. Alle ons bekende meetprocedures staan in deze waardelijst.
