### ISSUE TITLE
Onnauwkeurigheid door luchtdrukcorrectie

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GLD#36]
[Kees-Jan van der Made, voorzitter Vereniging Ondernemers Technisch Bodemonderzoek (VOTB)]
## Type issue
Publieke consultatie

## Waar
3.10.2 waterstand

## Samenvatting
Onnauwkeurigheid door onduidelijkheid datareeks voor luchtdrukcorrectie drukmetingen.

## Beschrijving
Veel metingen worden uitgevoerd met (absolute) druksensoren Voor druksensoren moet een luchtdrukcorrectie plaatsvinden. Hiervoor kunnen lokale metingen of die van KNMI stations gebruikt worden. Deze correctie geeft een extra (onbekende) onzekerheid.

## Oplossingsrichting
De mogelijkheid inbouwen in de BRO voor het opslaan van ruwe meetgegevens van (absolute) druksensoren (Inhangdiepte sensor (NAP), typesensor, meetnauwkeurigheid en meetbereik).
Een ervaren geohydroloog kan op basis van deze ruwe meetgegevens deze omzetten naar een grondwaterstandsreeks in NAP voor een specifiek project. Hij kan hiervoor zelf een luchtdrukreeks kiezen.

**Comment by harryvanmanen** [comment]
Dergelijke aanvullende (meta) gegevens moeten ergens een plek krijgen, bijvoorbeeld in IMO of een andere RuweDatabase buiten de BRO maar wel gekoppeld aan de BRO. Voor terugmeldingen en reproduceerbaarheid is dit noodzakelijk. Echter is het niet nodig (wenselijk) om alle informatie beschikbaar te stellen aan alle gebruikers, maar voor een deel alleen aan de bronhouder.

**Comment by AnnitaVijverberg** [comment]
Zie voor de beantwoording issue #35
