### ISSUE TITLE
Limietwaarde bij droogvallen buis

### ISSUE THREAD

**Issue by BJonkheid** [BROprogramma/GLD#41]
## Type issue
Publieke consultatie

## Waar
3.11.2, 3.11.3, pagina 22

## Samenvatting
Het is onduidelijk welke limietwaarde er opgegeven moet worden bij het droogvallen van een buis.

## Beschrijving
Als een buis droog staat is onduidelijk wat de juiste limietwaarde moet zijn. Bij het gebruik van een peilklokje is het redelijk om hiervoor de onderkant van de buis te gebruiken, maar bij drukmeters hangt het af van de positie van de meters in de buis, deze zijn niet in de BRO of in DINO vastgelegd. Het is niet bevredigend om hier de waarde bovenkant buis te gebruiken. 

## Oplossingsrichting
Voor nieuwe gegevens kan de bronhouder mogelijk zelf achterhalen was de positie van de drukmeters is. Voor IMBRO/A gegevens kan dit niet, is het mogelijk om geen limietwaarde op te geven?

**Comment by AnnitaVijverberg** [comment]
In hoofdstuk 3 van de gegevensdefinitie waarin de entiteiten en de attributen zijn gedefinieerd, kan onduidelijkheid bestaan welke niveaus als censuurlimietwaarde moeten worden opgegeven. Daarom wordt er in de toelichting in paragraaf 1.5.5.1 dieper op de censuurreden en censuurlimietwaarde ingegaan en welke niveaus veelal voor kunnen komen. Voor de limietwaarden gelden de niveaus van bovenkant monitoringbuis, maximaal meetbereik sensor, droogval sensor (of minimaal meetbereik), droogval filter, et cetera.

In geval van IMBRO/A mag de censuurreden ‘onbekend’ zijn en de censuurlimietwaarde mag leeg worden gelaten. Dit staat onder het attribuut censuurlimietwaarde als volgt als regel beschreven: 'Voor IMBRO/A gegevens ontbreekt de waarde wanneer het attribuut censuurreden de waarde onbekend heeft. Voor IMBRO/A-gegevens mag de waarde ontbreken wanneer het attribuut censuurreden de waarde groterDanLimietwaarde of kleinerDanLimietwaarde heeft.'
