### ISSUE TITLE
Altijd een voorlopige reeks naast een volledig beoordeelde reeks?

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GLD#43]
## Type issue
Publieke consultatie

## Samenvatting
Bij reguliere metingen zijn er twee opties voor de ‘mate van beoordeling’: ‘voorlopig’ en ‘volledig beoordeeld’. Moet er een voorlopige reeks zijn geregistreerd op het moment dat er corresponderende volledig beoordeelde reeks wordt aangeleverd?

## Beschrijving
Tijdens een van de workshops in het standaardisatieproces is de wens naar voren gekomen om onderscheid te maken in voorlopige gegevens en definitief beoordeelde gegevens. Dit komt met name voort uit de wens om gegevens snel beschikbaar te maken voor gebruikers. Met name bij telemetrie, maar ook als gegevens een paar keer per jaar van de datalogger worden uitgelezen, is er een mogelijkheid om gegevens in de BRO te registreren waarbij er nog geen volledige beoordeling heeft plaats gevonden. Die volledige beoordeling kan, afhankelijk van de gebruikte procedure, bijvoorbeeld pas een jaar na meten gedaan worden. Om de gegevens al voor die tijd beschikbaar te stellen aan gebruikers, worden ze als voorlopig geregistreerd in de BRO.

Daarmee rijst de vraag of er altijd sprake is van voorlopige gegevens. Ofwel, andersom benaderd: zijn er situaties waarbij er geen voorlopige reeks is maar direct een volledig beoordeelde reeks wordt geregistreerd? Te denken valt aan de praktijksituaties waarbij reguliere metingen plaatsvinden met behulp van een handapparaat:  worden die metingen gelijk als volledig beoordeeld in de BRO worden geregistreerd en is er dan dus geen sprake van een voorlopige reeks? Ons uitgangspunt is dat in principe uit de gebruikte beoordelingsprocedure is af te leiden wanneer (ongeveer) de volledige beoordeling kan plaats vinden. Als dit ‘lang’ na het meten pas gebeurt, kan gesteld worden dat er een voorlopige reeks geregistreerd moet worden.

Ons voorstel is dat we die praktijkgevallen waarin er sprake moet zijn van een voorlopige reeks gaan vastleggen in regels die tot de gegevensinhoud gaan behoren. Op basis van de analyse van de ons bekende beoordelingsprocedure betreft dit de volgende gevallen:
•	Het QCProtocol van de Provincies is gebruikt en als meetinstrument is een sensor gebruikt (dus niet  een apparaat voor een handmeting). 
•	Het validatie- en beoordelingsproces Brabant Water is gebruikt. In dit protocol zijn de reguliere handmetingen in buizen zonder drukopnemer buiten scope.

In de twee praktijkgevallen die hierboven worden beschreven gaat de BRO middels regels, op twee niveaus, het volgende afdwingen:
•	Er moeten voorlopige metingen aanwezig zijn als een bronhouder volledig beoordeelde gegevens wil registreren.
•	Het is verplicht om bij gegevens van een volledig beoordeelde reeks gerelateerde observaties te registreren. De gerelateerde observaties zijn de (observatie ID’s van) voorlopige reeks(en) die qua tijd corresponderen met de betreffende volledig beoordeelde reeks.

In alle andere gevallen is het aanleveren van voorlopige gegevens optioneel: het hangt van het beoordelingsproces af (het oordeel van een deskundige) of er vόόr de aanlevering van volledig beoordeelde gegevens al voorlopige gegevens beschikbaar zijn. Het al dan niet registreren van voorlopige tijd-meetwaarde reeksen wordt niet door de BRO afgedwongen.

**Comment by harryvanmanen** [comment]
Ik ben het eens dat voor "alle andere gevallen" het aanleveren van voorlopige gegevens optioneel is. maar ik ben het niet eens dat volgens de genoemde praktijkgevallen het wordt afgedwongen een voorlopige reeks aan te bieden. hieervoor moet ook de mogelijkheid zijn om direct de definitieve reeks aan te leveren. het is de verantwoording van de bronhouder om deze keuze te maken.

**Comment by AnnitaVijverberg** [comment]
[Jeroen Bernhard, Adviseur Monitoring Waterkwantiteit, hdsr]
"Ik snap de argumentatie niet waarom er altijd een voorlopige reeks zou moeten worden geregistreerd en ben het ook oneens dat het verplicht zou moeten zijn."

**Comment by AnnitaVijverberg** [comment]
[Platform Meetnetbeheerders, 12 provincies]
## Type issue
Publieke consultatie

## Beschrijving
Het wel/niet aanleveren van voorlopige metingen behoort optioneel te zijn. Het is aan de bronhouder om de afweging te maken of zijn/haar voorlopig beoordeelde gegevens geschikt zijn voor aanlevering aan de LV-BRO. Het concept achter voorlopige metingen is bedoeld om het mogelijk te maken actuele stijghoogten in de LV-BRO te kunnen zetten alszijnde "service" voor de BRO gebruiker. Daarbij hoort geen verplicht karakter m.b.t. de aanlevering.

## Oplossingsrichting
Voorlopige gegevens niet als verplicht stellen.

**Comment by AnnitaVijverberg** [comment]
Verschillende stakeholders hebben in github/per mail/telefonisch afkeurend gereageerd op deze voorstellen en bekrachtigen dit nogmaals tijdens de sprintreview: Het is niet wenselijk om deze verplichtingen überhaupt op te leggen, ook niet met de voorgestelde regels; het is de verantwoordelijkheid/keuze van de bronhouder om voorlopige metingen wel of niet te registreren. We hebben de toelichting en de gegevensdefinitie als aangepast: “Bij een observatie met een volledig beoordeelde tijd-meetwaardereeks moet daarom aangegeven worden dat de observatie gerelateerd is aan één of meer andere observaties indien deze gerelateerde observaties aanwezig zijn. De voorlopig beoordeelde observatie(s) waarop de volledig beoordeelde observatie is gebaseerd kan ontbreken. Ook controlemetingen die normaal gesproken gebruikt worden bij de beoordeling kunnen ontbreken. In deze gevallen kunnen gerelateerde observaties ontbreken.”
