### ISSUE TITLE
Waardelijst Datuminterval ontbreekt

### ISSUE THREAD

**Issue by swppulles** [BROprogramma/GLD#45]
## Type issue
Publieke consultatie

## Waar
3.5.2
## Samenvatting
Waardelijst Datuminterval ontbreekt

## Beschrijving
Deze waardelijst staat niet in artikel 2 vanaf blz. 24. Daarnaast de vraag waarom dit een _uitbreidbare_ waardelijst is, er moeten toch exact twee datums worden genoemd? 

## Oplossingsrichting
Niet-uitbreidbare waardelijst van maken, in het definitietabelletje 'begindatum' en 'einddatum' zetten, en opnemen in de catalogus.

**Comment by AnnitaVijverberg** [comment]
We hebben dit aangepast, inderdaad is DatumInterval geen type 'uitbreidbare waardelijst'. DatumInterval is een domein dat 2 data bevat namelijk een begindatum en een einddatum. In het document 'inleiding op de catalogus GLD' wordt een uitleg van dit type toegevoegd.
