### ISSUE TITLE
Waarom dubbel opvoeren van begin- en einddatum van Observatie

### ISSUE THREAD

**Issue by swppulles** [BROprogramma/GLD#46]
## Type issue
Publieke consultatie

## Waar
3.5.2

## Samenvatting
Waarom dubbel opvoeren van begin- en einddatum van Observatie

## Beschrijving
De begin- en einddatum van een observatie moeten in een brondocument worden opgegeven. Echter, deze gegevens zijn uit de meetdata te halen (Tijdmeetwaardepaar), wat m.i. onnodig werk oplevert. 

## Oplossingsrichting
De BRO dit gegeven zelf laten vullen aan de hand van de meetdata en in het domeinmodel 3.5 Observatie een / voor observatieperiode zetten.

**Comment by AnnitaVijverberg** [comment]
Zoals ook tijdens de sprintreview van 24 oktober is bediscussieerd en toegelicht moet, volgens de architectuurprincipes van de BRO, de inhoud van de BRO in principe door bronhouders worden aangeleverd en ‘zo min mogelijk’ door de LV BRO worden gegenereerd. Daarnaast is toen toegelicht dat met de voorgestelde werkwijze (aanleveren in brondocument) de WaterML standaard wordt gevolgd waardoor op WaterML gebaseerde software direct gebruikt kan worden. Als de BRO deze waarden toevoegt zou dergelijke software aangepast moeten worden. De overheid hecht veel waarde aan het gebruik van standaarden, omdat daarmee de samenwerking en gegevensuitwisseling tussen organisaties wordt vereenvoudigd en bevorderd. Er wordt met name (ook politiek) ingezet op het toepassen van open standaarden, WaterML is een
internationale, open standaard.
