### ISSUE TITLE
Attribuut datum metadata overbodig

### ISSUE THREAD

**Issue by swppulles** [BROprogramma/GLD#47]
## Type issue
Publieke consultatie

## Waar
3.6.1

## Samenvatting
Attribuut datum metadata overbodig

## Beschrijving
Het attribuut datum metadata in 3.6 Metadata observatie is overbodig omdat het direct afhankelijk is van het veld 3.5 Observatie.tijdstip resultaat. M.i. onnodig om dit apart op te geven. 

## Oplossingsrichting
Als het gegeven tóch in de BRO moet, kan de BRO het beter zelf afleiden na invoer van de data en kan er een / voor datum metadata in het domeinmodel 3.6 komen te staan.

**Comment by harryvanmanen** [comment]
dit attribuut kan (inderdaad) automatisch worden gevuld zodat een leverancier ontlast wordt.

**Comment by AnnitaVijverberg** [comment]
Datum metadata is in WaterML een verplicht attribuut. Omdat we ervoor gekozen hebben met GLD een profiel op WaterML te maken moet dit aangeleverd worden door de bronhouder/dataleverancier en kan het niet door de BRO afgeleid worden.
Zie ook issue #46
