### ISSUE TITLE
Organisatiegegevens uitvoerder wel of niet aan alle afnemers leveren?

### ISSUE THREAD

**Issue by swppulles** [BROprogramma/GLD#48]
## Type issue
Publieke consultatie
## Waar
Domeinmodel blz. 4, entiteiten 3.6 en 3.7

## Samenvatting
Organisatiegegevens uitvoerder wel of niet aan alle afnemers leveren?

## Beschrijving
In entiteit 3.6 staat een - voor uitvoerder (dus niet leveren aan alle afnemers) terwijl in 3.7 een + staat voor beide attributen die over die uitvoerder gaan (dus wél leveren). Als de dataleverancier-gegevens niet worden geleverd aan alle afnemers (zie entiteit Registratieobject in domeinmodel), lijkt het me logisch ook de uitvoerder-gegevens van de metingen niet te leveren. 

## Oplossingsrichting
In entiteit 3.7 de plustekens vervangen door mintekens. Of druist dit in tegen uml-conventies?

**Comment by AnnitaVijverberg** [comment]
Het klopt dat de gegevens over de uitvoerder niet uitgeleverd worden, behalve aan de bronhouder/dataleverancier. Dit is in het domeinmodel terug te vinden in de entiteit Metadata observatie. Daar staat het attribuut uitvoerder met een minteken ervoor. Omdat de uitvoerder bestaat uit een set van organisatiegegevens zie je dat terug in de entiteit Organisatiegegevens. De twee attributen in Organisatiegegevens hebben vanuit de hiërarchie het minteken geërfd van 'uitvoerder'. Het is echter niet gebruikelijk dat minteken te herhalen bij deze twee attributen.
