### ISSUE TITLE
toelichting 3.1.5 kwaliteitsregime

### ISSUE THREAD

**Issue by harryvanmanen** [BROprogramma/GLD#49]
## Type issue
Publieke consultatie

## Waar
3.1.5 kwaliteitsregime

## Samenvatting
toelichting kan duidelijker

## Beschrijving
Om direct te begrijpen wat wordt bedoeld hier toevoegen dat het IMBRO of IMBRO/A betreft

## Oplossingsrichting
toevoegen bij de toelichting: het betreft hier IMBRO of IMBRO/A

**Comment by AnnitaVijverberg** [comment]
Het is ongebruikelijk om de inhoud van de waardelijst te noemen in de definitie of de toelichting van een attribuut. Er is vermeld dat het een waardelijst betreft. De inhoud van alle waardelijsten is opgenomen in Artikel 2. We zien geen reden hiervan af te wijken bij kwaliteitsregime.
