### ISSUE TITLE
Datum beëindiging GLD

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GLD#51]
[Jelle Buma, geohydroloog van TNO]
## Type issue
Publieke consultatie

## Waar
paragraaf 3.2

## Beschrijving
Waar is te vinden of het GLD eventueel beeindigd is ? dat is nuttig om te weten als de datum van de recentste meting al een tijd geleden is: is er nog nieuwe data te verwachten of niet ?

## Oplossingsrichting
Extra attribuut bij entiteit Grondwaterstandsonderzoek

**Comment by swppulles** [comment]
Wordt dit niet gedekt door het attribuut registratiestatus in entiteit Registratiegeschiedenis? Dit attribuut kan de waarde voltooid hebben wat volgens de catalogus blz. 24 par 1.1. wil zeggen dat er geen nieuwe metingen kunnen worden geregistreerd. 
Wat ik mij wel afvraag is hoe de BRO erachter komt dat de registratiestatus op voltooid moet staan, want de bronhouder hoeft dit niet expliciet in een brondocument te melden. Volgens blz. 8 par 3.2  genereert de BRO de attribuut-waarde automatisch.

**Comment by AnnitaVijverberg** [comment]
Als het GLD beëindigd is, stuurt de bronhouder of dataleverancier een brondocument in: GLD-Voltooien. Van dat brondocument wordt automatisch de registratiestatus afgeleid: ‘voltooid’ en het ‘tijdstip voltooiing registratie’ wordt automatisch afgeleid van het moment van insturen van het bericht. Van een GLD met registratiestatus: voltooid zijn geen metingen meer te verwachten.

Overigens kan indien noodzakelijk een voltooid GLD met een correctiebericht weer opnieuw 'geactiveerd' worden.
