### ISSUE TITLE
IMBRO-kwaliteit = volledig beoordeeld en goedgekeurd

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GLD#52]
[Jelle Buma, geohydroloog van TNO]
## Type issue
Publieke consultatie

## Waar
paragraaf 3.6.3.

## Beschrijving
Naar mijn mening moet een meetreeks met IMBRO-kwaliteit volledig beoordeeld en goedgekeurd zijn. Dus geen of voorlopig betekent IMBRO/A.

## Oplossingsrichting
aanpassen cf. melding

**Comment by swppulles** [comment]
Ik denk dat dit niet kan want IMBRO/A heeft alleen betrekking op historische gegevens, of op projecten die vóór het van toepassing worden van de wet zijn gedefinieerd, maar tot metingen ná die datum leiden.

**Comment by AnnitaVijverberg** [comment]
De IMBRO/A-status heeft een wettelijke basis, en is gericht op historische gegevens waarvan geaccepteerd wordt dat een aantal formeel verplichte gegevens geen waarde heeft. Voor deze gegevens wordt het IMBRO/A-regime gehanteerd, dat dus minder strikte regels kent (zie ook paragraaf ‘2.4 Kwaliteitsregime’ van de inleiding op de catalogus. Vanaf het moment dat een registratieobject wettelijk gezien in werking treedt geldt vanaf dat moment voor ingewonnen gegevens de strikte regels van het IMBRO-regime. 
Ook voor nieuwe gegevens met mate beoordeling: ‘voorlopig’ dient de gegevensinhoud compleet te zijn en te voldoen aan het IMBRO-regime, hoewel de metingen zelf een mindere kwaliteit (kunnen) hebben. Deze (mogelijke) minder kwaliteit wordt door een aantal attributen vastgelegd: 
•	mate beoordeling: voorlopig
•	status kwaliteitscontrole: goedgekeurd, onbeslist, afgekeurd of nogNietBeoordeeld
Voorlopige gegevens hebben voor gebruikers grote waarde (zie ook de reactie van Stefan) en is er daarom voor gekozen om deze ook op te nemen in de BRO.
