### ISSUE TITLE
afgekeurde metingen zouden niet in de BRO moeten

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GLD#54]
[Jelle Buma, geohydroloog van TNO]
## Type issue
Publieke consultatie

## Waar
paragraaf 3.11.1

## Beschrijving
afgekeurde metingen zouden uberhaupt niet in de BRO moeten worden opgenomen. het leidt tot onnodige risico's. en indien status = onbeslist dan IMBRO/A.

## Oplossingsrichting
aanpassen cf. melding

**Comment by swppulles** [comment]
Door de attribuut-waarde afgekeurd kent de gebruiker de kwaliteit van de metingen, die echter niet per definitie volstrekt onbruikbaar hoeven te zijn. Ook afgekeurde metingen kunnen helpen bij globale beeldvorming over waterstanden. Het is wel de verantwoordelijkheid van de gebruiker wat hij ermee doet.

**Comment by AnnitaVijverberg** [comment]
Het standaardisatieteam is zich er terdege van bewust dat afgekeurde en goedgekeurde gegevens niet door elkaar gehaald moeten worden. Voor en tijdens de totstandkoming van de catalogi van de registratieobjecten GLD en GAR (waar de status kwaliteitscontrole ook is opgenomen) is dit onderwerp dan ook uitgebreid onderbouwd, afgewogen, bediscussieerd en afgestemd met stakeholders, zowel tijdens sprintreviews als specifieke workshops over dit onderwerp. Uit dat proces is deze oplossing als beste naar voren gekomen, omdat:
a) de risico’s in praktijk goed oplosbaar en hanteerbaar zijn, bijv. via de manier van uitgifte. 
b) het beoordelingsproces (deels) subjectief is 
c) voortschrijdend inzicht t.a.v. kwaliteitsoordeel niet ongebruikelijk is
d) het aanleveren van ALLE gegevens het meest transparant is, wat onderdeel is van het 12 eisenstelsel van basisregistraties
e) bij het aanleveren van ALLE gegevens eenduidig voldaan wordt aan de wettelijke leverplicht
Om bovengenoemde redenen blijven we erbij dat deze oplossing al met al te prefereren is boven dit of andere alternatieven die ingebracht zijn.
