### ISSUE TITLE
attribuut 'interpolatietype' verwijderen

### ISSUE THREAD

**Issue by AnnitaVijverberg** [BROprogramma/GLD#55]
[Jelle Buma, geohydroloog van TNO]
## Type issue
Publieke consultatie

## Waar
paragraaf 3.11.4

## Beschrijving
dit attribuut zou overbodig moeten zijn. een interpolatie is een modeltype en resulteert niet in zuivere meetwaarden.

## Oplossingsrichting
attribuut verwijderen

**Comment by swppulles** [comment]
Mee eens. 
Er kan vooralsnog alleen discontinu worden ingevuld wat inhoudt dat er alleen feitelijke, zuivere meetwaarden kunnen worden aangeleverd. 
Wellicht is dit attribuut al ingebouwd met het oog op toekomstige inzichten, maar het heeft nu geen toegevoegde waarde.

**Comment by AnnitaVijverberg** [comment]
Inderdaad gaat interpolatietype over modelleren en niet over zuivere meetwaarde.  Daarom wordt hier altijd ‘discontinu’ ingevuld: we in de basisregistratie ondergrond de feitelijke waarnemingen vastleggen. Het is aan de gebruiker te beoordelen of en hoe hij de meetwaarden eventueel wil interpoleren of aggregeren.

Interpolatietype is een in WaterML verplicht attribuut, daarom moet het aangeleverd worden en kan het niet worden ingevuld door de BRO (zie ook issue #46).
