### ISSUE TITLE
Beschikbaar stellen voorlopige reeks

### ISSUE THREAD

**Issue by harryvanmanen** [BROprogramma/GLD#57]
## Type issue
Publieke consultatie
## Waar 
3.6.3 mate beoordeling

## Samenvatting
Voorlopige reeks beperkt beschikbaar stellen

## Beschrijving
Voorlopige reeks moet na opwaardering tot volledig beoordeelde reeks alleen voor bronhouder inzichtelijk zijn. 

## Oplossingsrichting
Na opwaardering alleen voor bronhouder beschikbaar stellen

**Comment by AnnitaVijverberg** [comment]
We zijn ons bewust van het feit dat gebruikers is vrijwel alle gevallen gebruik moeten maken van de definitief beoordeelde reeks indien deze beschikbaar is. We hebben hiervoor de paragraaf Hiërarchie in gebruiksplicht (1.6 van de toelichting) opgenomen. Het blijft, onder andere omwille van de transparantie (onderdeel van het 12 eisenstelsel van basisregistraties), wel mogelijk om voorlopige reeksen in te zien.
