### ISSUE TITLE
Gecorrigeerd voor IMBRO/A niet mogelijk

### ISSUE THREAD

**Issue by harryvanmanen** [BROprogramma/GLD#58]
## Type issue
Publieke consultatie

## Waar
3.2.5 gecorrigeerd

## Samenvatting
Voor IMBRO/A is het niet mogelijk dit attribuut aan te leveren

## Beschrijving
Voor historische reeksen (IMBRO/A) is het niet realistisch om te veronderstellen dat bekend is of er verbeteringen/correcties hebben plaatsgevonden 

## Oplossingsrichting
"Onbekend" toevoegen als mogelijkheid voor IMBRO/A.
Dit heeft relatie met 3.2.6 tijdstip laatste correctie.

**Comment by AnnitaVijverberg** [comment]
Het attribuut ‘gecorrigeerd’ (ja/nee) wordt automatisch gegenereerd door de basisregistratie ondergrond. Het wordt niet aangeleverd door de bronhouder/dataleverancier. Het maakt onderdeel uit van de registratiegeschiedenis die in elk BRO registratieobject aanwezig is. Wanneer al geregistreerde gegevens worden gecorrigeerd, is het feit dat er is gecorrigeerd terug te vinden bij het attribuut gecorrigeerd, daar staat ‘ja’. Het gaat er hier dus om of de gegevens in de BRO zijn gecorrigeerd, het geeft niet weer of de gegevens door de uitvoerende meetinstantie, de dataleverancier of de bronhouder voor aanlevering aan de BRO zijn gecorrigeerd.
