### ISSUE TITLE
Kardinaliteit Oberservatie onduidelijk

### ISSUE THREAD

**Issue by harryvanmanen** [BROprogramma/GLD#59]
## Type issue
Publieke consultatie

## Waar
3.5 Observatie

## Samenvatting
Kardinaliteit met andere entiteiten onduidelijk

## Beschrijving
Bij "relaties met andere entiteiten" is vermeld dat Observatie is gerelateerd aan 0..* Observatie. => dit klopt niet met  het domeinmodel, er is onduidelijk wat wordt bedoeld.

## Oplossingsrichting
aanpassen of toelichten

**Comment by AnnitaVijverberg** [comment]
In het domeinmodel is toegevoegd dat het om 0..* gerelateerde observaties gaat. 
Bij een observatie met een volledig beoordeelde tijd-meetwaardereeks bijvoorbeeld moet geregistreerd worden dat de observatie gerelateerd is aan één of meer andere observaties indien deze gerelateerde observaties aanwezig zijn. De voorlopig beoordeelde observatie(s) waarop de volledig beoordeelde observatie is gebaseerd kan ontbreken. Ook controlemetingen die normaal gesproken gebruikt worden bij de beoordeling kunnen ontbreken. In deze gevallen kunnen gerelateerde observaties ontbreken. Vandaar dat gerelateerde observaties 0 keer, 1 keer of meer keer kunnen voorkomen.
