### ISSUE TITLE
Datuminterval Observatieperiode

### ISSUE THREAD

**Issue by harryvanmanen** [BROprogramma/GLD#60]
## Type issue
Publieke consultatie

## Waar
3.5.2 observatieperiode

## Samenvatting
Onduidelijk waarom Datuminterval als waardelijst wordt aangegeven

## Beschrijving
Er wordt aangegeven dat de Waardelijst uitbreidbaar is. Het betreft Datuminterval, en het is mij niet duidelijk waarom een datuminterval uitbreidbaar is en waarom deze waardelijst niet is opgenomen in artkel 2.

## Oplossingsrichting
Toelichten/verduidelijken.
Ook kan het datuminterval van de observatie automatisch bepaald worden door het systeem zodat de dataleverancier daar geen "last" van heeft.

**Comment by AnnitaVijverberg** [comment]
We hebben dit aangepast, inderdaad is DatumInterval geen type 'uitbreidbare waardelijst'. DatumInterval is een domein dat bestaat uit een begindatum en een einddatum.
Zie #46 voor een toelichting en waarom de BRO dit gegeven niet afleidt.
