### ISSUE TITLE
Tijdstip resultaat automatisch bepalen en toelichten

### ISSUE THREAD

**Issue by harryvanmanen** [BROprogramma/GLD#61]
## Type issue
Publieke consultatie

## Waar
3.5.3 tijdstip resultaat

## Samenvatting
Dit attribuut kan automatisch worden bepaald

## Beschrijving
Dit attribuut kan automatisch worden bepaald, en ook is het onduidelijk waarom dit attribuut is opgenomen.

## Oplossingsrichting
Automatisch laten bepalen en toelichten waarom dit attribuut is opgenomen

**Comment by AnnitaVijverberg** [comment]
Het attribuut is een in waterML verplicht attribuut. De bronhouder moet het daarom aanleveren (zie een verdere toelichting hierover #46). We hebben de tekst van paragraaf 1.5.2 van de toelichting (over de observatie waaronder het tijdstip resultaat)  aangevuld om dit attribuut te verduidelijken.
