### ISSUE TITLE
Kardinaliteit beoordelingsprocedure

### ISSUE THREAD

**Issue by harryvanmanen** [BROprogramma/GLD#62]
## Type issue
Publieke consultatie

## Waar
3.8.6 beoordelingsprocedure

## Samenvatting
Kardinaliteit moet 1..* zijn

## Beschrijving
Er kan slechts 1 beoordelingsprocedure worden opgenomen terwijl er in sommige situatie en bij sommige bronhouders meerdere procedures mogelijk zijn, bijvoorbeeld Provincieprotocol + AAT

## Oplossingsrichting
Kardinaliteit aanpassen

**Comment by AnnitaVijverberg** [comment]
Uitgangspunt bij alle procedures in de BRO is dat er 1 gebruikte procedure gekozen kan worden. Het is overigens wel gebruikelijk dat procedures naar elkaar verwijzen. In procedure A staat bijvoorbeeld dat voor een bepaald onderdeel van een proces gewerkt wordt volgens procedure B. 
Zie ook issue #67. Is AAT hier wel een procedure of betreft dit een software tool?
