### ISSUE TITLE
tijdreeds ID is overbodig

### ISSUE THREAD

**Issue by harryvanmanen** [BROprogramma/GLD#63]
## Type issue
Publieke consultatie

## Waar
3.9.1 tijdreeks ID

## Samenvatting
het attribuut tijdreeks ID is overbodig

## Beschrijving
het attribuut tijdreeks ID is overbodig omdat ook observatie ID beschikbaar is en onder obersevatie ID altijd 1 tijdreeks gekoppeld is.

## Oplossingsrichting
kan vervallen of hiervoor observatie ID gebruiken (maar dan weinig toevoegd)

**Comment by AnnitaVijverberg** [comment]
Tijdreeks ID is hernoemd naar tijdmeetwaardereeks ID om verwarring te voorkomen, het komt nu overeen met de naam van de entiteit (Tijdmeetwaardereeks).

Het attribuut is vanuit WaterML (en Observations & Measurements) verplicht. Daarnaast is het een zeer bruikbaar attribuut, met name bij eventuele correcties: Wanneer correcties in de meetwaarde(n) moeten worden geregistreerd, kan gebruik gemaakt worden van het tijdmeetwaardereeks ID, dan hoeven de overige gegevens van de observatie (zoals observatietype, uitvoerder en observatieproceskenmerken) niet bij de correctie niet opnieuw aangeleverd te worden. Bij een correctie van meetwaarden wordt in dit geval verwezen naar het betreffende tijdmeetwaardereeks ID en wordt deze reeks opnieuw aangeleverd, zonder de kenmerken van de observatie.

Zie ook issue #106
