### ISSUE TITLE
Grondwaterstanden op zee

### ISSUE THREAD

**Issue by harryvanmanen** [BROprogramma/GLD#64]
## Type issue
Publieke consultatie

## Waar
3.10.2 waterstand

## Samenvatting
op zee kunnen ook grondwaterstanden (stijghoogten) gemeten worden. De eenheid wijkt dan af van metingen op het land.

## Beschrijving
op zee kunnen ook grondwaterstanden (stijghoogten) gemeten worden. In de inleiding staat dat dan USL of LAT gebruikt moet worden. dat is niet wenselijk.

## Oplossingsrichting
alle grondwaterstanden opnemen t.o.v. NAP

**Comment by AnnitaVijverberg** [comment]
Harry: "Het gaat om het openhouden van de mogelijkheid om grondwaterpeilen te meten. Ik ken momenteel geen actuele metingen op zee. Je kunt denken de uitstroom van zoet grondwater richting de zee. Qua constructie denk je dan aan een combinatie met golfmeetpalen of andere platforms."

**Comment by AnnitaVijverberg** [comment]
In de algemene inleiding staat ook "De BRO hanteert bij inname de meest recente versie van de UNCLOS-basislijn en controleert daarmee of de juiste referentiestelsels gebruikt worden." Deze basislijn geeft aan of een locatie land of zee is. De Waddenzee valt onder land. De vraag is dit scenario op dit moment een issue is daar er geen putten bekend zijn die op zee liggen.

We sluiten op dit moment dit issue. Uit de implementatie zal blijken of en wanneer zich een situatie gaat voor doen dat dit een issue is. Dan wordt het opnieuw bekeken.
