### ISSUE TITLE
Waarde van censuur meetwaarde

### ISSUE THREAD

**Issue by harryvanmanen** [BROprogramma/GLD#65]
## Type issue
Publieke consultatie

## Waar
3.11.2 censuurreden

## Samenvatting
 Censuurmeetwaarden moeten een herkenbare waarde krijgen

## Beschrijving
De censuurmeetwaarde moet een herkenbare waarde toegekend worden. Dat is voor verwerking/presentaties en analyses wenselijk. 
## Oplossingsrichting
Dat kan bijvoorbeeld zijn -99 voor onderschrijding, +99 voor overschrijding, of de werkelijk boven- en onderdrempel van betrouwbaar meetwaardebereik.

**Comment by AnnitaVijverberg** [comment]
De waterstand zelf krijgt in het geval er een censuurreden is geen waarde. De censuurreden is groterDanLimietwaarde of kleinerDanLimietwaarde en bij de censuurlimietwaarde wordt de werkelijke waarde ingevuld waarvan met zekerheid gezegd kan worden dat de werkelijke waterstand zich daaronder of daarboven bevind. Bijvoorbeeld is de  censuurlimietwaarde de inhangdiepte van de sensor (in meter ten opzichte van NAP) bij een drooggevallen sensor.
