### ISSUE TITLE
Interpolatietype  "continue reeks" niet in waardelijst

### ISSUE THREAD

**Issue by harryvanmanen** [BROprogramma/GLD#66]
## Type issue
Publieke consultatie 

## Waar
3.11.4 interpolatietype

## Samenvatting
In waardelijst ontbreekt "continue reeks"

## Beschrijving
Er wordt gesteld dat voor het interpolatietype een vaste waarde "discontinu" wordt ingevuld. Echter wordt ook de mogelijkheid geboden om "continu" te gebruiken. Deze laatste is echter niet opgenomen in de waardelijst.

## Oplossingsrichting
waardelijst aanpassen

**Comment by AnnitaVijverberg** [comment]
Wat bedoeld wordt, is dat de BRO in GLD alleen feitelijke waarnemingen vast legt en dat daarom bij interpolatietype alleen ‘discontinu’ aangeleverd kan worden. Zie ook issue #55 .
Om verwarring te voorkomen hebben we de toevoeging: “Het is aan de gebruiker te beoordelen of er mogelijk sprake is van een continue reeks.” weggehaald uit de toelichting in de gegevensdefinitie. Een uitgebreide toelichting staat in de laatste alinea van paragraaf 1.5.5.1. staat dit nader toegelicht.
