### ISSUE TITLE
Aanvulling waardelijst Beoordelingsprocedure

### ISSUE THREAD

**Issue by harryvanmanen** [BROprogramma/GLD#67]
## Type issue
Publieke consultatie 

## Waar
1.6 beoordelingsprocedure blz 26

## Samenvatting
uitbreiden waardelijst met AAT (RWS)

## Beschrijving
In de waardelijst ontbreekt "AAT (RWS)", omschrijving "De beoordeling is uitgevoerd met de Automatische Audit Tool van Rijkswaterstaat

## Oplossingsrichting
De waardelijst uitbreiden met "AAT (RWS)", omschrijving "De beoordeling is uitgevoerd met de Automatische Audit Tool van Rijkswaterstaat

**Comment by AnnitaVijverberg** [comment]
Voor de BRO als basisregistratie is het belangrijk dat de inhoudelijke definitie van gegevens duidelijk en eenduidig is. De gegevensinhoud dient bijvoorbeeld ook bestand te zijn tegen de ‘tand des tijds’. Dit geldt voor gegevens in het algemeen, en dus ook voor de inhoud en elementen van waardelijsten in het bijzonder.

Voor bijv. een afnemer van de BRO wint een gegeven als beoordelingsprocedure: ‘AAT (RWS)’ aan betekenis en duidelijkheid indien deze beoordelingsprocedure gedocumenteerd is. Een procedure is daarbij in beginsel iets anders dan software die al dan niet bij de beoordeling gebruikt is. Software en tools zijn hulpmiddelen, die over het algemeen op verschillende manieren ingezet kunnen worden. Zowel procedures als software kunnen daarnaast onderhevig zijn aan veranderingen. Om de inhoud van een beoordelingsprocedure eenduidig te maken én te houden, verdient het de voorkeur om bijv. een versienummer of jaartal van documentatie daaraan toe te voegen.

In hoeverre bestaat er een gedocumenteerde beoordelingsprocedure waarin beschreven wordt hoe een beoordeling met behulp van de Automatische Audit Tool van Rijkswaterstaat precies te werk gaat, dan wel in hoeverre kan een dergelijk document opgesteld worden?

**Comment by AnnitaVijverberg** [comment]
AAT is op dit moment een tool en geen procedure maar is voornemens om de rekenregels van AAT om te zetten in eisen die worden opgenomen in een procedure met een versienummer:
Voorstel van RWS voor de waarde: RWS_AATgrondwater1.0
Omschrijving: De kwaliteitscontrole is uitgevoerd op basis van AAT (Automatische Audit Tool) eisen/regels van Rijkswaterstaat.

**Comment by AnnitaVijverberg** [comment]
We hebben het protocol opgenomen. We hebben de naamgeving en omschrijving wat aangepast om het meer in overeenkomst met de naamgeving van de andere items en volgens onze 'spelregels voor definities' te maken.
