### ISSUE TITLE
Afgekeurde reeks niet opnemen in BRO

### ISSUE THREAD

**Issue by harryvanmanen** [BROprogramma/GLD#68]
## Type issue
Publieke consultatie

## Waar
3.11.1 status kwaliteitscontrole

## Samenvatting
 Meetwaarden Kwaliteitscontrole afgekeurd niet opnemen in BRO

## Beschrijving
Meetwaarden met Statuskwaliteitscontrole "afgekeurd" moeten niet worden opgenomen (of tenminste niet zichtbaar worden voor gebruikers). het betreft bijvoorbeeld delen van een reeks die absoluut onbruikbaar zijn als gevolg van een storing van het apparaat. In de BRO horen alleen gegevens van goede kwaliteit en verschillende interpretatie door verschillende gebruikers is niet gewenst. Ik wil als gebruiker alleen de betrouwbare informatie. 

## Oplossingsrichting
Meetwaarden met Statuskwaliteitscontrole "afgekeurd" niet opnemen (of tenminste niet zichtbaar worden voor gebruikers). en daarvoor kan bij censuurreden de reden opnemen.

**Comment by AnnitaVijverberg** [comment]
Het standaardisatieteam is zich er terdege van bewust dat afgekeurde en goedgekeurde gegevens niet door elkaar gehaald moeten worden. Voor en tijdens de totstandkoming van de catalogi van de registratieobjecten GLD en GAR (waar attribuut status kwaliteitscontrole ook is opgenomen) is dit onderwerp dan ook uitgebreid onderbouwd, afgewogen, bediscussieerd en afgestemd met stakeholders, zowel tijdens sprintreviews als specifieke workshops over dit onderwerp. Uit dat proces is deze oplossing als beste naar voren gekomen, omdat:

1. de risico’s in praktijk goed oplosbaar en hanteerbaar zijn, bijv. via de manier van uitgifte.
2. het beoordelingsproces (deels) subjectief is 
3. voortschrijdend inzicht t.a.v. kwaliteitsoordeel niet ongebruikelijk is
4. het aanleveren van ALLE gegevens het meest transparant is, wat één van de eisen is in het 12 eisenstelsel van basisregistraties
5. bij het aanleveren van ALLE gegevens eenduidig voldaan wordt aan de wettelijke leverplicht

Om bovengenoemde redenen prefereren we nog steeds de gekozen oplossing waarbij in de waardelijst StatusKwaliteitscontrole ook de waarde Afgekeurd opgenomen is. Bij uitgifte én visualisatie zal bekeken worden hoe het onderscheid tussen gegevens met een verschillende waarde voor attribuut status kwaliteitscontrole voor de gebruiker uit elkaar gehouden en duidelijk gemaakt kan worden.
