### ISSUE TITLE
Waardelijst Meetprocedure uitbreiden

### ISSUE THREAD

**Issue by harryvanmanen** [BROprogramma/GLD#70]
## Type issue
Publieke consultatie]

## Waar
1.2 Meetprocedure

## Samenvatting
Uitbreiding waardelijst Meetprocedure

## Beschrijving
Wens om Waardelijst uitbreiding met NEN 5766, SIKB protocollen 2001 en 2101

## Oplossingsrichting
Waardelijst uitbreiden met:

- NEN 5766: 2019, Nederlandse norm Bodem - Plaatsing van peilbuizen ten behoeve van milieukundig bodemonderzoek; De norm beschrijft het plaatsen van peilbuizen
- SIKB protocol 2001, Plaatsen van handboringen en peilbuizen, maken van boorbeschrijvingen, nemen van grondmonsters en waterpassen. 
- SIKB protocol 2101, dit protocol geeft voorschriften voor mechanisch boren

**Comment by AnnitaVijverberg** [comment]
Deze normen en protocollen zijn ons bekend. Het betreffen uitsluitend normen voor het plaatsen van peilbuizen (putten) en zijn daarmee niet van toepassing op het meten van grondwaterstanden in putten. Om deze reden worden de genoemde normen en protocollen niet opgenomen in de waardelijst.
Bij NEN5766 komt (naast het plaatsen van peilbuizen) ook het bepalen van stijghoogte aan bod. In deze norm wordt echter nadrukkelink verwezen naar NEN5120 (bepaling van stijghoogten van grondwater door middel van peilbuizen). Deze norm staat wel in de waardelijst. Hij is sinds 2009 ingetrokken en daarom alleen voor IMBRO/A gegvens te kiezen.

SIKB2001 - gaat niet over meten van grondwaterstanden
SIKB2101 - gaat niet over meten van grondwaterstanden
NEN5766 - Op hoofdlijn beschreven dat een watertsand in een peilbuis kan worden gemeten. Verwijzing naar NEN5120
NEN5120 - ingetrokken en vervangen door NEN-EN-ISO22475. Beide normen zijn vermeld in de waardelijst meetprocedure.
