### ISSUE TITLE
Observatieperiode kan overlap hebben

### ISSUE THREAD

**Issue by JosVonAsmuth** [BROprogramma/GLD#71]
## Type issue
Publieke consultatie

## Waar
Paragraaf 3.5.2 observatieperiode, regels

## Samenvatting
Een observatieperiode kan (in het geval van voorlopige gegevens) een overlap hebben met een vorige, wanneer de klok van bijv. de datalogger een tijdsverschuiving heeft.

## Beschrijving
Bij het uitlezen van een datalogger kan de loggerklok gesynchroniseerd worden. Wanneer de tijdsverschuiving groter is dan het meetinterval en positief is, doet zich een overlap voor.

## Oplossingsrichting
Overlap in de observatieperiode van voorlopige observaties toestaan.

**Comment by AnnitaVijverberg** [comment]
We gaan ervan uit dat na een definitieve beoordeling, een eventuele verschuiving in de tijd door een niet goed functionerende klok is aangepast. Dat betekent dat in de definitief beoordeelde reeks de regel dat er geen overlap mogelijk is, kan blijven. Bij een voorlopige reeks en (een reeks) controlemeting hebben we die regel weggehaald. Dat is aangepast in de toelichtende tekst en in de gegevensdefinitie.
